var atores = {
  A: [
    "Anya Taylor-Joy",
    "Adam Driver",
    "Alicia Vikander",
    "Austin Butler",
    "Ana de Armas",
    "Amy Adams",
    "Andrew Garfield",
    "Anne Hathaway",
    "Anthony Hopkins",
    "Ariana Grande",
    "Ashton Kutcher",
    "Anthony Ramos",
  ],
  B: [
    "Bradley Cooper",
    "Brie Larson",
    "Blake Lively",
    "Bill Skarsgård",
    "Bella Hadid",
    "Benedict Cumberbatch",
    "Ben Affleck",
    "Beyoncé",
    "Brandon Perea",
    "Britt Robertson",
  ],
  C: [
    "Chris Hemsworth",
    "Claire Foy",
    "Constance Wu",
    "Cuba Gooding Jr.",
    "Chris Evans",
    "Cate Blanchett",
    "Chadwick Boseman",
    "Cardi B",
    "Cillian Murphy",
    "Chris Pratt",
    "Charlize Theron",
    "Colin Farrell",
    "Christopher Reeve",
    "Chloe Grace Moretz",
  ],
  D: [
    "Daniel Craig",
    "Dakota Johnson",
    "Dwayne Johnson",
    "Zendaya",
    "Diego Luna",
    "Daniel Radcliffe",
    "Drew Barrymore",
    "Daisy Edgar-Jones",
    "David Corenswet",
    "Daryl McCormack",
  ],
  E: [
    "Eddie Redmayne",
    "Emma Watson",
    "Emilia Clarke",
    "Ezra Miller",
    "Elizabeth Olsen",
    "Emma Stone",
    "Eva Green",
    "Emily Blunt",
    "Evan Peters",
    "Elle Fanning",
  ],
  F: [
    "Florence Pugh",
    "Freida Pinto",
    "Finn Wolfhard",
    "Forest Whitaker",
    "Freddie Highmore",
    "Frank Quitely",
    "Frances McDormand",
    "Felicity Jones",
    "Freida Pinto",
    "Freddie Prinze Jr.",
  ],
  G: [
    "Gemma Chan",
    "Gal Gadot",
    "Giancarlo Esposito",
    "Glenn Close",
    "Gillian Anderson",
    "Glen Powell",
    "Grant Morrison",
    "Gary Frank",
    "Gugu Mbatha-Raw",
    "Gaspard Ulliel",
  ],
  H: [
    "Harrison Ford",
    "Hugh Jackman",
    "Henry Cavill",
    "Helen Mirren",
    "Halle Berry",
    "Harry Styles",
    "Hailee Steinfeld",
    "Haley Bennett",
    "Hugh Laurie",
    "Hiroyuki Sanada",
  ],
  I: [
    "Idris Elba",
    "Isla Fisher",
    "Ian McKellen",
    "Imelda Staunton",
    "Ivana Baquero",
    "Isaac Hempstead Wright",
    "Iain Glen",
    "Iko Uwais",
    "Imogen Poots",
    "Ilana Glazer",
  ],
  J: [
    "Jake Gyllenhaal",
    "Jamie Foxx",
    "Jason Momoa",
    "Jared Leto",
    "Jennifer Lawrence",
    "Jennifer Aniston",
    "James McAvoy",
    "Joaquin Phoenix",
    "Joe Dante",
    "John Landis",
    "Jessie Buckley",
  ],
  K: [
    "Keanu Reeves",
    "Kristen Stewart",
    "Kerry Washington",
    "Kevin Hart",
    "Kirsten Dunst",
    "Kumail Nanjiani",
    "Katherine Langford",
    "Kurt Russell",
    "Keira Knightley",
    "Kiernan Shipka",
  ],
  L: [
    "Lady Gaga",
    "Lupita Nyong'o",
    "Leonardo DiCaprio",
    "Liam Neeson",
    "Lucy Liu",
    "Lee Isaac Chung",
    "Léa Seydoux",
    "Laura Dern",
    "Lily Collins",
    "Lena Headey",
  ],
  M: [
    "Margot Robbie",
    "Michael B. Jordan",
    "Matthew McConaughey",
    "Mila Kunis",
    "Meryl Streep",
    "Mark L. Smith",
    "Michael Crichton",
    "Maggie Gyllenhaal",
    "Maura Tierney",
    "Mackenzie Davis",
  ],
  N: [
    "Natalie Portman",
    "Nicole Kidman",
    "Neil Patrick Harris",
    "Naomi Watts",
    "Nicolas Cage",
    "Noah Centineo",
    "Naomie Harris",
    "Natalia Dyer",
    "Nick Robinson",
    "Nikolaj Coster-Waldau",
  ],
  O: [
    "Olivia Wilde",
    "Oscar Isaac",
    "Octavia Spencer",
    "Orlando Bloom",
    "Olivia Colman",
    "Owen Wilson",
    "Olga Kurylenko",
    "Omari Hardwick",
    "Octavia Butler",
    "Odessa Young",
  ],
  P: [
    "Paul Rudd",
    "Pedro Pascal",
    "Penélope Cruz",
    "Priyanka Chopra",
    "Patrick Stewart",
    "Peter Sarsgaard",
    "Pablo Schreiber",
    "Patricia Clarkson",
    "Phoebe Waller-Bridge",
    "Pom Klementieff",
  ],
  Q: [
    "Queen Latifah",
    "Quincy Jones",
    "Quentin Tarantino",
    "Quvenzhane Wallis",
    "Quincy Brown",
    "Quinn Shephard",
    "Quinton Aaron",
    "Q'orianka Kilcher",
    "Quentin Dupieux",
    "Quinn Lord",
  ],
  R: [
    "Robert Pattinson",
    "Ryan Gosling",
    "Ryan Reynolds",
    "Rami Malek",
    "Reese Witherspoon",
    "Rachel Brosnahan",
    "Richard Donner",
    "Robin Wright",
    "Riz Ahmed",
    "Rachael Taylor",
  ],
  S: [
    "Samuel L. Jackson",
    "Saoirse Ronan",
    "Scarlett Johansson",
    "Sebastian Stan",
    "Seth Rogen",
    "Shia LaBeouf",
    "Sienna Miller",
    "Sigourney Weaver",
    "Sophie Turner",
    "Stanley Tucci",
    "Stephen Fry",
    "Steve Carell",
    "Susan Sarandon",
    "Sylvester Stallone",
    "Steven Spielberg",
    "Sally Rooney",
    "Skyler Gisondo",
    "Sasha Lane",
    "Simon Kinberg",
  ],
  T: [
    "Tessa Thompson",
    "Timothée Chalamet",
    "Tom Holland",
    "Taron Egerton",
    "Tiffany Haddish",
    "Tom Hanks",
    "Tilda Swinton",
    "Tyler Perry",
    "Tom Hardy",
    "Tatiana Maslany",
  ],
  U: [
    "Uma Thurman",
    "Ursula Corberó",
    "Uzo Aduba",
    "Ulrich Thomsen",
    "Usher",
    "Udo Kier",
    "Ulla Bergryd",
    "Uschi Glas",
    "Utkarsh Ambudkar",
    "Ursula Andress",
  ],
  V: [
    "Viola Davis",
    "Vin Diesel",
    "Vanessa Hudgens",
    "Viggo Mortensen",
    "Victoria Justice",
    "Vera Farmiga",
    "Val Kilmer",
    "Vince Vaughn",
    "Vivica A. Fox",
    "Vicky Krieps",
  ],
  W: [
    "Will Ferrell",
    "Woody Allen",
    "Winona Ryder",
    "Willem Dafoe",
    "William H. Macy",
    "Wagner Moura",
    "Wes Anderson",
    "Wesley Snipes",
    "Winona Ryder",
    "Will Smith",
  ],
  X: [
    "Xavier Dolan",
    "Xander Berkeley",
    "Xzibit",
    "Xosha Roquemore",
    "Ximena Duque",
    "Xavier Samuel",
    "Xenia Goodwin",
    "Ximena Navarrete",
    "Xia Vigor",
    "Xosha Roquemore",
  ],
  Y: [
    "Yahya Abdul-Mateen II",
    "Yalitza Aparicio",
    "Yvonne Strahovski",
    "Yara Shahidi",
    "Yasmine Bleeth",
    "Yara Martinez",
    "Yeardley Smith",
    "Yvette Nicole Brown",
    "Yvonne De Carlo",
    "Yasmine Al Massri",
  ],
  Z: [
    "Zendaya",
    "Zoe Saldana",
    "Zachary Quinto",
    "Zach Galifianakis",
    "Zazie Beetz",
    "Zara Larsson",
    "Zhang Ziyi",
    "Zoey Deutch",
    "Zoe Kravitz",
    "Zuleikha Robinson",
  ],
};
